### ISSUE TITLE
Create UX

### ISSUE THREAD

**Issue by osu-sustainability** [OSU-Sustainability-Office/sustainability_map_old#9]
The Sustainability Map needs a new frontend framework & UI to support newly-planned features. 

This UI must support:
 - Mobile Devices
 - Firefox, Chrome, & Safari
 - ADA Accessibility
 - Google Maps API
 - Data point filtering using a search bar, and url parameters

This UI must include:
 - A large map, with colored dots representing data points.
 - Some sort of default data (Sustainability Tour, unless specified in url by the user)
 - A way to organize data by "expanding" data that's located "beneath" a point. This can be accomplished by a relational database.

**Comment by jackrwoods** [comment]
During the meeting, we discussed using the Corvallis Bus App (on the Google Play Store) as a source for UI inspiration.
